### ISSUE TITLE
Previous version published in the newer one

### ISSUE THREAD

**Issue by mensfeld** [sandreae/jekyll-hoffnung3000#2]
Hey,

While inspecting this package, I noticed that you publish the previous version in newer. In this case 0.1.4 package was added to the 0.1.5 release.

ref https://my.diffend.io/gems/jekyll-hoffnung3000/0.1.4/0.1.5#d2h-202032

**Comment by sandreae** [comment]
Hi, thanks for noticing and raising this issue, this is my first gem, so it's much appreciated.

Fixed the issue in next release.

S

**Comment by mensfeld** [comment]
Good luck on your gems adventure :) if you would have any problems ins releasing / managing gems, you can always ping me!

**Comment by sandreae** [comment]
Thanks! :pray:
